name: fmi_schedule
description: A new Flutter project for FMI schedule.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  workmanager: ^0.5.2
  flutter_local_notifications: ^16.3.0
  geolocator: ^12.0.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
